# Generated by Django 2.2.6 on 2020-03-01 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(default='mysql', max_length=48, verbose_name='数据库类型')),
                ('host', models.CharField(max_length=100, verbose_name='ip地址')),
                ('port', models.PositiveIntegerField(default=3306, verbose_name='端口号')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
            ],
            options={
                'verbose_name': '数据库信息配置表',
                'verbose_name_plural': '数据库信息配置表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='url')),
                ('sub_menu', models.BooleanField(default=False, verbose_name='是否有下级菜单')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '导航菜单表',
                'verbose_name_plural': '导航菜单表',
            },
        ),
    ]
