# Generated by Django 2.2.6 on 2020-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_type', models.CharField(max_length=30, verbose_name='代理类型')),
                ('host', models.CharField(max_length=100, verbose_name='ip地址')),
                ('port', models.CharField(max_length=30, verbose_name='端口')),
                ('score', models.PositiveIntegerField(verbose_name='得分')),
                ('valid_time', models.DateTimeField(verbose_name='验证时间')),
            ],
            options={
                'verbose_name': '免费代理',
                'verbose_name_plural': '免费代理',
            },
        ),
    ]
